modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MattCzyr/NaturesCompass/issues"

[[mods]]
    modId="naturescompass"
    version="${file.jarVersion}"
    displayName="Nature's Compass"
    displayURL="https://github.com/MattCzyr/NaturesCompass"
    authors="ChaosTheDude"
    description='''
    Search for a biome and get information about it.
    '''

[[dependencies.naturescompass]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
